### ISSUE TITLE
CIRM czi Conversion Failure

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/microscopy#25]
The `czi2dzi.py` script is failing for some CIRM *.czi files. For example:
```
Can not convert czi to dzi for "/var/www/data/20150213-mKD12.5eWnt11W1-OM-0-06-000/06cc373230e8f677609c5fae2370096726771a2c578251c55dc6937264ec343d".
stdoutdata: 
stderrdata: CZI B=1 S=3 T=1 C=4 Z=3 Y=22243 X=90166 0=1 tile-size 2040x2040 uint16
  channels: DAPI (DAPI #FF0000FF), AF480 (Alexa Fluor 488 #FF00FF33), AF555 (Alexa Fluor 555 #FFFF0000), AF647 (Alexa Fluor 647 #FFFFFF00)
  bounding-box: ((23868, -119340), (46132, -29140)) native or shape 22264x90200
  zoom levels: [1, 2, 4, 8, 16, 32]
Estimating 50 tiles per row at zoom level 1 or 151 tile cache size
Image reported microns per pixel: {'Y': 0.3243778432965572, 'X': 0.3243778432965572, 'Z': 2.5}
Channel 0 zoom 1: Canvas 90200x22264 using 177x44 output grid of 512x512 q=75 tiles
Channel 0 zoom 2: Canvas 45100x11132 using 89x22 output grid of 512x512 q=75 tiles
Channel 0 zoom 4: Canvas 22550x5566 using 45x11 output grid of 512x512 q=75 tiles
Channel 0 zoom 8: Canvas 11275x2783 using 23x6 output grid of 512x512 q=75 tiles
Channel 0 zoom 16: Canvas 5637x1391 using 12x3 output grid of 512x512 q=75 tiles
Channel 0 zoom 32: Canvas 2818x695 using 6x2 output grid of 512x512 q=75 tiles
Traceback (most recent call last):
  File "/usr/bin/czi2dzi.py", line 538, in <module>
    ret = main(*sys.argv[1:])
  File "/usr/bin/czi2dzi.py", line 496, in main
    metadata_to_xml(doc, channel, dzichanneldirname)
  File "/usr/bin/czi2dzi.py", line 376, in metadata_to_xml
    assert len(mpps) == 1
AssertionError
```
The czi file can be got from the `hatrac` database on `cirm-staging`.

**Comment by karlcz** [comment]
It looks like this one will be an easy fix.  The file reports a microns-per-pixel for the Z dimension and this is different from the X and Y values.  I think we can just discard it and report the XY microns-per-pixel that is relevant to the 2D viewier.

**Comment by karlcz** [comment]
See 563555285b80e9c0c5ec0cd8321a1012d1f29f15 which should allow conversion to succeed for this case.

**Comment by svoinea** [comment]
Re-installed czi2dzi.
Tested and works as expected.
