### ISSUE TITLE
CIRM czi Conversion Failure (2)

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/microscopy#26]
Another `czi2dzi.py` failure for a CIRM czi file (maybe it is related to #25 ):

```
Can not convert czi to dzi for "/var/www/data/20140901-IRI_7d_6-JL-0-81-000/015ccb5f09b720b2a187e877c5be598f4c4e7190d5de95d41a88524180808250".
stdoutdata: 
stderrdata: Traceback (most recent call last):
  File "/usr/bin/czi2dzi.py", line 538, in <module>
    ret = main(*sys.argv[1:])
  File "/usr/bin/czi2dzi.py", line 423, in main
    converter = LazyCziConverter(czifilename)
  File "/usr/bin/czi2dzi.py", line 109, in __init__
    for i in range(self._fo.shape[self._C])
IndexError: list index out of range
```

**Comment by karlcz** [comment]
This one seems like the CZI file lacks channel information that we expect.  It's going to take more effort to see whether this is a different form of metadata or if this is simply a file we don't expect to handle...

**Comment by karlcz** [comment]
I added a more explicit assertion check to report why this is failing.  I notice there are two objects in hatrac with the same prefix `20140901-IRI_7d_6-JL-0-81-000` but different checksums.  One of these converts successfully and the other fails like this.

Are they different scans of the same slide?  If so, you should check with the user as to whether one of these scans might be invalid for some other reason...  if they consider it valid and it is important to convert, we'll need to continue work here to find out what difference there is in the metadata structure and how to cope with it.

**Comment by robes** [comment]
@svoinea can you update this issue? are we still seeing this error?

**Comment by svoinea** [comment]
Based on the content of the `czi` file, such errors are still possible, or others like:
```
found no Metadata/DisplaySetting/Channels/Channel elements in CZI metadata
```
or:
```
can not read ZISRAW segment
```

The single solution I see in such cases is to ask them to resend the `czi` file(s).
