### ISSUE TITLE
czifile.czifile.SegmentNotFoundError: can not read ZISRAW segment

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/microscopy#27]
```
Can not convert czi to dzi for "/var/www/data/20140301-SW wt kidney-JL-0-61-000/125b1ec239969f1ad4628b152323b910a94c8bbbcf5e248a37acffac5f24f2c4".
stdoutdata:
stderrdata: Traceback (most recent call last):
  File "/usr/bin/czi2dzi.py", line 542, in <module>
    ret = main(*sys.argv[1:])
  File "/usr/bin/czi2dzi.py", line 427, in main
    converter = LazyCziConverter(czifilename)
  File "/usr/bin/czi2dzi.py", line 19, in __init__
    self._Z = self._fo.axes.find('Z')
  File "/usr/lib64/python2.7/site-packages/tifffile/tifffile.py", line 1149, in __get__
    value = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/czifile/czifile.py", line 347, in axes
    return self.filtered_subblock_directory[0].axes
  File "/usr/lib64/python2.7/site-packages/tifffile/tifffile.py", line 1149, in __get__
    value = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/czifile/czifile.py", line 314, in filtered_subblock_directory
    for directory_entry in self.subblock_directory
  File "/usr/lib64/python2.7/site-packages/tifffile/tifffile.py", line 1149, in __get__
    value = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/czifile/czifile.py", line 266, in subblock_directory
    segment = Segment(self._fh, self.header.directory_position)
  File "/usr/lib64/python2.7/site-packages/czifile/czifile.py", line 427, in __init__
    raise SegmentNotFoundError("can not read ZISRAW segment")
czifile.czifile.SegmentNotFoundError: can not read ZISRAW segment
```
 - the file was initially uploaded on piranha with Globus Transfer on 2015-10-02.
 - it has 16.65GB
 - the file was uploaded from piranha on cirm-staging on 2016-08-14 and the size is identical with the one on piranha

Things to be checked:

1. Is the file we have identical to the file Seth has (rule out possible
   iobox/hatrac transfer corruption)

2. Does the file open properly for Seth using his Zeiss software?

3. Does Seth have any idea why the file is different than others, i.e.
   is it saved with different Zeiss version or options?

4. Is it important for us to handle this file?

**Comment by svoinea** [comment]
Seth has re-saved from ZEN the `125b1ec239969f1ad4628b152323b910a94c8bbbcf5e248a37acffac5f24f2c4.czi` file.
This new one (200MB less than the previous one) was valid for the third-party czifile file format reader library.
